name: User Story
description: Create a new User Story
labels: ["Type::User Story", "On Refinement Board"]

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the field below to define the User Story.
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      value: |
        As a
        I want to
        So that
  - type: textarea
    id: summary
    attributes:
      label: Summary
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
  - type: input
    id: approver
    attributes:
      label: Approver
